add reset functions
espressif/esptool-js pull request #100
Opened 2023-06-14 12:26 UTC by brianignacio5

Move reset code to a separate file and add multiple reset modes: classic, usb jtag and custom.

Fix #76

2023-06-15 01:24 UTC, balloob approved these changes

2023-06-15 10:33 UTC, igrr approved these changes

2023-06-15 14:20 UTC, radurentea requested changes
Left a comment on how we could get rid off an any type

2023-06-15 14:20 UTC, radurentea commented on src/reset.ts
We could avoid the 'any' type on line 95, doing the following modifications:

```typescript
type CmdsArgsTypes = {
  D: boolean;
  R: boolean;
  W: number;
};

export async function customReset(transport: Transport, sequenceString: string) {
  const resetDictionary: { [K in keyof CmdsArgsTypes]: (arg: CmdsArgsTypes[K]) => Promise<void> } = {
      D: async (arg: boolean) => await transport.setDTR(arg),
      R: async (arg: boolean) => await transport.setRTS(arg),
      W: async (delay: number) => await sleep(delay),
  };
  try {
      const isValidSequence = validateCustomResetStringSequence(sequenceString);
      if (!isValidSequence) {
          return;
      }
      const cmds = sequenceString.split("|");
      for (const cmd of cmds) {
          const cmdKey = cmd[0];
          const cmdVal = cmd.slice(1);
          if (cmdKey === 'W') {
              await resetDictionary['W'](Number(cmdVal));
          } else if (cmdKey === 'D' || cmdKey === 'R') {
              await resetDictionary[cmdKey as 'D' | 'R'](cmdVal === '1');
          }
      }
  } catch (error) {
      throw new Error("Invalid custom reset sequence");
  }
}
```

2023-06-21 12:06 UTC, radurentea approved these changes

2023-06-30 06:27 UTC, merged