Feature/support esp32h2
espressif/esptool-js pull request #102
Opened 2023-06-21 06:10 UTC by adwait-esp

- Ported the changes from esptools.py for esp32h2 chipset.
- Tested with H2 chipset and able to flash firmware image on h2 using the tool.

2023-06-21 06:46 UTC, igrr approved these changes
LGTM! Just one lint issue to fix so that pipeline passes.

2023-06-21 11:24 UTC, brianignacio5 requested changes
LGTM with small change

2023-06-21 11:24 UTC, brianignacio5 commented on src/esploader.ts
> +    case 0xD7B73E80:{
`case 0xd7b73e80`

2023-06-22 11:37 UTC, adwait-esp commented on src/esploader.ts
> +    case 0xD7B73E80:{
Fixed

2023-06-23 11:21 UTC, adwait-esp commented
Merging since the minor review comments are addressed and CI pipeline job has succeeded as well

2023-06-23 11:28 UTC, merged