Re-enable block timeout calculation
espressif/esptool-js pull request #83
Opened 2023-01-25 19:57 UTC by igrr

Block write timeout is generally determined by the time it takes to erase and write the data into flash. Since that time is proportional to the amount of uncompressed data written, we need to keep track of the number of bytes each chunk is decompressed into.

Re-enable the commented out code block, based on a suggestion (from Mark Adler, no less!) in https://stackoverflow.com/a/73096372.

* Replaces https://github.com/espressif/esptool-js/pull/57
* Fixes https://github.com/espressif/esptool-js/issues/49

2023-01-29 08:46 UTC, brianignacio5 requested changes
LGTM with few changes.

2023-01-29 08:46 UTC, brianignacio5 commented on src/esploader.ts
> +import Pako, { deflate, Inflate } from "pako";
Suggest change imports to `import { Data, deflate, inflate } from "pako";`

2023-01-29 08:46 UTC, brianignacio5 commented on src/esploader.ts
> +      inflate.onData = function (chunk: Pako.Data): void {
Also this to `chunk: Data`

2023-02-03 19:17 UTC, balloob commented
Could we have a new release once this is merged? 🙏

2023-02-09 02:14 UTC, brianignacio5 approved these changes
LGTM

2023-02-09 16:15 UTC, merged

2023-02-12 20:54 UTC, balloob commented
🎉 

Would you have time for a release this week?

2023-02-20 14:37 UTC, balloob commented
@igrr last time I'll ask, but could we get a release with this fix? Now that the repo has been migrated to TypeScript, we can no longer point our dependency at a git commit

2023-02-20 14:40 UTC, igrr commented
@balloob I sorry for the delay! We have talked with @brianignacio5 about preparing the new release, but it seems like there is some issue in the release workflow that needs to be fixed, and neither of us has had time to look into this yet, unfortunately!

2023-02-28 15:29 UTC, Jason2866 commented
@balloob release is done :-)